KULRICE-8208 - DeprecatedDocumentTagsTest.testDocTypeSecurityAndResponsibilityAndVisibilityWorkgroupNames rule attribute field does not have the expected visibility expected:<false> but was:<true>
git-svn-id: https://svn.kuali.org/repos/rice/branches/rice-2.1@34812 7a7aa7f6-c479-11dc-97e2-85a2497f191d